# Generated by Django 4.0.2 on 2022-02-27 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_orderstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dataUpdated', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=200, verbose_name='first name')),
                ('lastName', models.CharField(max_length=200, verbose_name='last name')),
                ('phoneNumberOne', models.CharField(max_length=200, verbose_name='phone number one')),
                ('phoneNumberTwo', models.CharField(blank=True, max_length=200, null=True, verbose_name='phone number two')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='email')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='street')),
                ('detailedAddress', models.CharField(blank=True, max_length=400, null=True, verbose_name='detailed address')),
                ('additionalInformation', models.CharField(blank=True, max_length=400, null=True, verbose_name='additional information')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ecommerce.city')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
