# Generated by Django 4.0.2 on 2022-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phoneNumberOne',
            field=models.CharField(max_length=11, verbose_name='phone number one'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phoneNumberTwo',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number two'),
        ),
    ]
